# Generated by Django 3.1.3 on 2020-12-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodworks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_woodworks',
            field=models.ManyToManyField(through='woodworks.Like', to='woodworks.Woodwork'),
        ),
    ]
