# Generated by Django 3.1.3 on 2020-11-25 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Woodwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('main_image', models.FileField(null=True, upload_to='woodworks/static/woodworks_image')),
            ],
            options={
                'db_table': 'woodworks',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('woodwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woodworks.woodwork')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
