# Generated by Django 3.1.3 on 2020-12-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_liked_woodworks'),
        ('woodworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_at', models.DateTimeField()),
                ('status', models.TextField(choices=[('received', 'Ricevuto'), ('confirmed', 'Confermato'), ('pending', 'Lavoro in corso'), ('done', 'Fatto, in attesa di consegna'), ('delivered', 'Consegnato')], default='received', max_length=255)),
                ('notes', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('woodwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='woodworks.woodwork')),
            ],
        ),
    ]
