# Generated by Django 3.1.3 on 2020-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodwork',
            name='main_image',
            field=models.TextField(null=True),
        ),
    ]
