# Generated by Django 3.1.3 on 2020-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodworks', '0002_woodwork_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodwork',
            name='main_image',
            field=models.FileField(null=True, upload_to='woodworks_image'),
        ),
    ]
