# Generated by Django 3.1.3 on 2020-12-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodworks', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
