# Generated by Django 3.1.3 on 2020-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodworks', '0003_auto_20201201_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
