# Generated by Django 3.1.3 on 2020-11-22 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woodworks', '0004_auto_20201112_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('woodwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woodworks.woodwork')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
