# Generated by Django 3.1.3 on 2020-12-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_liked_woodworks'),
        ('woodworks', '0004_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiration_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
