# Generated by Django 3.1.3 on 2020-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_liked_woodworks'),
        ('woodworks', '0005_auto_20201202_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='woodwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woodworks.woodwork'),
        ),
    ]
